{% set version = "2023.09.0" %}

package:
  name: geocat-viz
  version: {{ version }}

source:
  url: https://github.com/NCAR/geocat-viz/archive/v{{ version }}.tar.gz   # For building from a specific tag's tarball
  sha256: b3c75c23c2fb7eeb87255e2022a40a8d11fa3444e45beafd4dcea7c5cc5cc1a9

build:
  noarch: python
  number: 0
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .

requirements:
  host:
    - python >=3.8, <3.11
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=3.8, <3.11
    - cartopy
    - cmaps
    - matplotlib
    - metpy
    - numpy
    - scikit-learn
    - xarray

test:
  imports:
    - geocat
    - geocat.viz
  commands:
    # print package version
    - python -c "import geocat.viz; print(geocat.viz.__version__)"

about:
  home: https://geocat.ucar.edu/
  summary: GeoCAT-viz is a collection of utility functions to make Python plotting with Matplotlib and Cartopy more like NCL (NCAR Command Language).
  dev_url: https://github.com/NCAR/geocat-viz
  doc_url: https://geocat-viz.readthedocs.io
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - NCAR/geocat # GeoCAT https://github.com/orgs/NCAR/teams/geocat
    - anissa111 # A. Zacharias https://github.com/anissa111
    - erogluorhan # O. Eroglu https://github.com/erogluorhan
    - jukent # J. Kent https://github.com/jukent/
    - kafitzgerald # K. FitzGerald https://github.com/kafitzgerald
